import type { AdminUser } from '../types/auth';
import type { AppUser } from '../types/users';
import type { NotificationCampaign, AudienceSegmentDefinition } from '../types/notifications';
import type { CrashIssue, CrashMetricsSummary } from '../types/crashlytics';
import type { AuditLogEntry } from '../types/audit';

export const INITIAL_ADMINS: AdminUser[] = [
  {
    uid: 'gbkvVPrf8UPbN0i8QZWaGT2B4K62',
    email: 'test@admin.com',
    displayName: 'Staff Admin (test@admin.com)',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'app_manager',
    isSuperAdmin: false,
    firestorePermissions: {
      sendNotifications: true,
      userEdit: true,
      userEmailView: true,
      userView: true,
    },
    customClaims: {
      role: 'app_manager',
      isSuperAdmin: false,
      permissions: [
        'users:view',
        'users:view_email',
        'users:edit',
        'users:manage_subscription',
        'users:edit_messages',
        'fcm:compose',
        'fcm:broadcast',
        'fcm:view_campaigns',
      ],
      department: 'Operations',
      securityClearance: 'tier_2',
      adminSince: '2024-01-15T00:00:00Z',
    },
    status: 'active',
    lastLogin: '2026-08-14T07:45:12Z',
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    uid: 'admin_sarah_super',
    email: 'sarah.almansoor@tijarah.app',
    displayName: 'Sarah Al-Mansoor (Super Admin)',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'super_admin',
    isSuperAdmin: true,
    firestorePermissions: {
      sendNotifications: true,
      userEdit: true,
      userEmailView: true,
      userView: true,
    },
    customClaims: {
      role: 'super_admin',
      isSuperAdmin: true,
      permissions: [
        'users:view', 'users:view_email', 'users:edit', 'users:manage_subscription', 'users:edit_messages',
        'users:delete', 'users:export', 'fcm:compose', 'fcm:broadcast', 'fcm:view_campaigns',
        'fcm:manage_segments', 'crashlytics:view', 'crashlytics:manage_issues',
        'analytics:app_health', 'analytics:financial', 'admins:view', 'admins:manage_roles',
        'admins:set_claims', 'audit:view_full', 'settings:manage',
      ],
      department: 'Executive Engineering',
      securityClearance: 'tier_1',
      adminSince: '2023-01-15T00:00:00Z',
    },
    status: 'active',
    lastLogin: '2026-08-14T07:45:12Z',
    createdAt: '2023-01-15T09:00:00Z',
  },
  {
    uid: 'admin_chloe_mkt',
    email: 'chloe.dupont@tijarah.app',
    displayName: 'Chloe Dupont (Marketing)',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    role: 'marketing_admin',
    isSuperAdmin: false,
    firestorePermissions: {
      sendNotifications: true,
      userEdit: false,
      userEmailView: false,
      userView: false,
    },
    customClaims: {
      role: 'marketing_admin',
      isSuperAdmin: false,
      permissions: [
        'fcm:compose', 'fcm:broadcast', 'fcm:view_campaigns', 'fcm:manage_segments', 'audit:view_limited',
      ],
      department: 'Growth & Retention',
      securityClearance: 'tier_3',
      adminSince: '2024-09-01T00:00:00Z',
    },
    status: 'active',
    lastLogin: '2026-08-13T16:30:20Z',
    createdAt: '2024-09-01T14:15:00Z',
  },
];

export const INITIAL_USERS: AppUser[] = [
  {
    id: 'usr_shafi_001',
    firstName: 'shafi',
    lastName: 'munshi',
    name: 'shafi munshi',
    email: 'test@mail.com',
    phone: '01300100574',
    phoneNumber: '01300100574',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=shafi',
    is_premium: 1,
    tier: 'pro',
    expire_date: '2027-11-12',
    tierExpiresAt: '2027-11-12T00:00:00Z',
    expireAt: '2027-11-12T00:00:00Z',
    expiresAt: '2027-11-12T00:00:00Z',
    messageRemaining: 75,
    pinCode: '1111',
    isVerified: true,
    role: 0,
    autoRenew: true,
    status: 'active',
    joinedAt: '2025-01-10T12:00:00Z',
    lastActiveAt: '2026-08-14T07:22:00Z',
    devicesCount: 2,
    ordersCount: 48,
    totalSpent: 4250.00,
    fcmTokenCount: 2,
    country: 'Bangladesh',
    notes: 'Premium merchant with 75 SMS message credits remaining.',
    storageQuotaMb: 5120,
    usedStorageMb: 1420,
  },
  {
    id: 'usr_8921a4f',
    firstName: 'Karim',
    lastName: 'Bensalem',
    name: 'Karim Bensalem',
    email: 'karim.bensalem@enterprise.sa',
    phone: '+966 50 123 4567',
    phoneNumber: '+966 50 123 4567',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    is_premium: 1,
    tier: 'enterprise',
    expire_date: '2027-12-31',
    tierExpiresAt: '2027-12-31T23:59:59Z',
    expireAt: '2027-12-31T23:59:59Z',
    expiresAt: '2027-12-31T23:59:59Z',
    messageRemaining: 340,
    pinCode: '2024',
    isVerified: true,
    role: 0,
    autoRenew: true,
    status: 'active',
    joinedAt: '2024-02-14T10:20:00Z',
    lastActiveAt: '2026-08-14T07:22:00Z',
    devicesCount: 3,
    ordersCount: 412,
    totalSpent: 38450.00,
    fcmTokenCount: 3,
    country: 'Saudi Arabia',
    notes: 'Key wholesale merchant in Riyadh.',
    storageQuotaMb: 10240,
    usedStorageMb: 4210,
  },
  {
    id: 'usr_3910c2e',
    firstName: 'Amira',
    lastName: 'Al-Husseini',
    name: 'Amira Al-Husseini',
    email: 'amira.fashion@boutique.ae',
    phone: '+971 52 987 6543',
    phoneNumber: '+971 52 987 6543',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    is_premium: 1,
    tier: 'pro',
    expire_date: '2026-11-15',
    tierExpiresAt: '2026-11-15T00:00:00Z',
    expireAt: '2026-11-15T00:00:00Z',
    expiresAt: '2026-11-15T00:00:00Z',
    messageRemaining: 120,
    pinCode: '8899',
    isVerified: true,
    role: 0,
    autoRenew: true,
    status: 'active',
    joinedAt: '2024-08-01T14:10:00Z',
    lastActiveAt: '2026-08-14T06:45:00Z',
    devicesCount: 2,
    ordersCount: 89,
    totalSpent: 9240.50,
    fcmTokenCount: 2,
    country: 'United Arab Emirates',
    notes: 'Dubai flagship boutique merchant.',
    storageQuotaMb: 5120,
    usedStorageMb: 1980,
  },
  {
    id: 'usr_5182f7d',
    firstName: 'Yousef',
    lastName: 'Nader',
    name: 'Yousef Nader',
    email: 'yousef.nader@gmail.com',
    phone: '+965 99 876 543',
    phoneNumber: '+965 99 876 543',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    is_premium: 0,
    tier: 'free',
    expire_date: '',
    tierExpiresAt: null,
    expireAt: null,
    expiresAt: null,
    messageRemaining: 10,
    pinCode: '0000',
    isVerified: false,
    role: 0,
    autoRenew: false,
    status: 'active',
    joinedAt: '2025-01-10T12:00:00Z',
    lastActiveAt: '2026-08-13T19:15:00Z',
    devicesCount: 1,
    ordersCount: 14,
    totalSpent: 620.00,
    fcmTokenCount: 1,
    country: 'Kuwait',
    notes: 'Retail buyer experimenting with localized shop.',
    storageQuotaMb: 1024,
    usedStorageMb: 410,
  },
];

export const AUDIENCE_SEGMENTS: AudienceSegmentDefinition[] = [
  {
    id: 'all_users',
    name: 'All Registered Users',
    description: 'Broadcast to all active mobile device push tokens across iOS & Android.',
    estimatedCount: 184500,
    icon: 'Users',
    category: 'activity',
  },
  {
    id: 'pro_subscribers',
    name: 'Pro & Enterprise Tier',
    description: 'High-value paying subscribers eligible for VIP perks and beta feature previews.',
    estimatedCount: 28400,
    icon: 'Crown',
    category: 'tier',
  },
  {
    id: 'inactive_7_days',
    name: 'Dormant (> 7 Days Inactive)',
    description: 'Re-engagement segment for users who opened the app over a week ago.',
    estimatedCount: 42100,
    icon: 'UserX',
    category: 'activity',
  },
  {
    id: 'ios_users',
    name: 'iOS Apple Devices (APNs)',
    description: 'Devices registered with Apple APNs payload handlers and live badges.',
    estimatedCount: 98700,
    icon: 'Smartphone',
    category: 'platform',
  },
  {
    id: 'android_users',
    name: 'Android Devices (FCM v1)',
    description: 'Devices registered via standard Google Play Services push channels.',
    estimatedCount: 85800,
    icon: 'Smartphone',
    category: 'platform',
  },
  {
    id: 'high_value_spenders',
    name: 'Top 10% Spenders',
    description: 'Merchants and power shoppers with lifetime orders exceeding $5,000.',
    estimatedCount: 14200,
    icon: 'TrendingUp',
    category: 'behavior',
  },
];

export const INITIAL_CAMPAIGNS: NotificationCampaign[] = [
  {
    id: 'camp_7819_summer',
    title: '🎉 Summer Flash Sale: Up to 40% Off!',
    body: 'Exclusive weekend discounts on your top saved merchant catalogs. Tap to explore!',
    imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&auto=format&fit=crop&q=80',
    deepLink: 'tijarah://promotions/summer_2026',
    audience: 'all_users',
    audienceEstimatedCount: 184500,
    status: 'completed',
    priority: 'high',
    sound: 'alert',
    createdAt: '2026-08-10T10:00:00Z',
    sentAt: '2026-08-10T14:00:00Z',
    createdBy: {
      adminId: 'admin_chloe_mkt',
      adminName: 'Chloe Dupont',
      adminRole: 'Marketing Admin',
    },
    metrics: {
      totalSent: 184500,
      deliveredCount: 178920,
      openedCount: 42350,
      clickedCount: 29400,
      failedCount: 5580,
      deliveryRatePct: 96.9,
      openRatePct: 23.7,
    },
  },
];

export const INITIAL_CRASH_ISSUES: CrashIssue[] = [
  {
    id: 'issue_cr_4091',
    title: 'NullPointerException in PaymentSheetPresenter.onSuccess',
    subtitle: 'com.tijarah.app.checkout.PaymentSheetPresenter.kt:142',
    exceptionType: 'java.lang.NullPointerException',
    severity: 'fatal',
    status: 'investigating',
    firstSeen: '2026-08-11T12:30:00Z',
    lastSeen: '2026-08-14T07:15:00Z',
    totalEvents: 342,
    impactedUsersCount: 188,
    affectedVersions: ['v3.4.1', 'v3.4.2'],
    assignedTo: 'david.chen@tijarah.app',
    rootCauseNotes: 'Happens when gateway callback returns nullable receipt object on slow 3G connectivity.',
    stackTrace: [
      'java.lang.NullPointerException: Parameter specified as non-null is null: method com.tijarah.app.checkout.ReceiptData.<init>',
      '  at com.tijarah.app.checkout.PaymentSheetPresenter.onSuccess(PaymentSheetPresenter.kt:142)',
      '  at com.tijarah.core.network.StripeCallbackHandler.onResult(StripeCallbackHandler.kt:89)',
    ],
  },
];

export const INITIAL_CRASH_METRICS: CrashMetricsSummary = {
  crashFreeUsersPct: 99.78,
  crashFreeSessionsPct: 99.91,
  totalCrashes24h: 37,
  openIssuesCount: 2,
  anrCount24h: 3,
  topOffendingVersion: 'v3.4.2 (Android)',
};

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud_99182',
    timestamp: '2026-08-14T07:45:10Z',
    action: 'admin_custom_claims_updated',
    actor: {
      uid: 'admin_sarah_super',
      displayName: 'Sarah Al-Mansoor',
      email: 'sarah.almansoor@tijarah.app',
      role: 'super_admin',
    },
    targetResource: {
      type: 'admin',
      id: 'gbkvVPrf8UPbN0i8QZWaGT2B4K62',
      name: 'test@admin.com',
    },
    description: 'Updated admin permissions from ADMINS collection.',
    changes: {
      before: null,
      after: { isSuperAdmin: false, userEdit: true, sendNotifications: true },
    },
    ipAddress: '192.168.1.104',
  },
];
