import type { AdminUser } from '../types/auth';
import type { AppUser } from '../types/users';
import type { NotificationCampaign, AudienceSegmentDefinition } from '../types/notifications';
import type { CrashIssue, CrashMetricsSummary } from '../types/crashlytics';
import type { AuditLogEntry } from '../types/audit';

export const INITIAL_ADMINS: AdminUser[] = [
  {
    uid: 'admin_sarah_super',
    email: 'sarah.almansoor@tijarah.app',
    displayName: 'Sarah Al-Mansoor',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'super_admin',
    customClaims: {
      role: 'super_admin',
      permissions: [
        'users:view',
        'users:edit',
        'users:manage_subscription',
        'users:delete',
        'users:export',
        'fcm:compose',
        'fcm:broadcast',
        'fcm:view_campaigns',
        'fcm:manage_segments',
        'crashlytics:view',
        'crashlytics:manage_issues',
        'analytics:app_health',
        'analytics:financial',
        'admins:view',
        'admins:manage_roles',
        'admins:set_claims',
        'audit:view_full',
        'settings:manage',
      ],
      department: 'Executive Engineering',
      securityClearance: 'tier_1',
      adminSince: '2023-01-15T00:00:00Z',
    },
    status: 'active',
    lastLogin: '2026-08-14T07:45:12Z',
    createdAt: '2023-01-15T09:00:00Z',
  },
  {
    uid: 'admin_david_pm',
    email: 'david.chen@tijarah.app',
    displayName: 'David Chen',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'app_manager',
    customClaims: {
      role: 'app_manager',
      permissions: [
        'users:view',
        'users:edit',
        'users:manage_subscription',
        'crashlytics:view',
        'crashlytics:manage_issues',
        'analytics:app_health',
        'audit:view_limited',
      ],
      department: 'Product Operations',
      securityClearance: 'tier_2',
      adminSince: '2024-03-10T00:00:00Z',
    },
    status: 'active',
    lastLogin: '2026-08-14T06:12:00Z',
    createdAt: '2024-03-10T11:20:00Z',
  },
  {
    uid: 'admin_chloe_mkt',
    email: 'chloe.dupont@tijarah.app',
    displayName: 'Chloe Dupont',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    role: 'marketing_admin',
    customClaims: {
      role: 'marketing_admin',
      permissions: [
        'fcm:compose',
        'fcm:broadcast',
        'fcm:view_campaigns',
        'fcm:manage_segments',
        'audit:view_limited',
      ],
      department: 'Growth & Retention',
      securityClearance: 'tier_3',
      adminSince: '2024-09-01T00:00:00Z',
    },
    status: 'active',
    lastLogin: '2026-08-13T16:30:20Z',
    createdAt: '2024-09-01T14:15:00Z',
  },
  {
    uid: 'admin_tariq_sec',
    email: 'tariq.zayed@tijarah.app',
    displayName: 'Tariq Zayed',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'super_admin',
    customClaims: {
      role: 'super_admin',
      permissions: [
        'users:view', 'users:edit', 'users:manage_subscription', 'users:delete', 'users:export',
        'fcm:compose', 'fcm:broadcast', 'fcm:view_campaigns', 'fcm:manage_segments',
        'crashlytics:view', 'crashlytics:manage_issues', 'analytics:app_health', 'analytics:financial',
        'admins:view', 'admins:manage_roles', 'admins:set_claims', 'audit:view_full', 'settings:manage'
      ],
      department: 'Cloud & Infosec',
      securityClearance: 'tier_1',
      adminSince: '2023-06-20T00:00:00Z',
    },
    status: 'active',
    lastLogin: '2026-08-12T10:00:00Z',
    createdAt: '2023-06-20T08:00:00Z',
  },
];

export const INITIAL_USERS: AppUser[] = [
  {
    id: 'usr_8921a4f',
    name: 'Karim Bensalem',
    email: 'karim.bensalem@enterprise.sa',
    phoneNumber: '+966 50 123 4567',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    tier: 'enterprise',
    tierExpiresAt: '2027-12-31T23:59:59Z',
    autoRenew: true,
    status: 'active',
    joinedAt: '2024-02-14T10:20:00Z',
    lastActiveAt: '2026-08-14T07:22:00Z',
    devicesCount: 3,
    ordersCount: 412,
    totalSpent: 38450.00,
    fcmTokenCount: 3,
    country: 'Saudi Arabia',
    notes: 'Key wholesale merchant in Riyadh. High API throughput requirement.',
    storageQuotaMb: 10240,
    usedStorageMb: 4210,
  },
  {
    id: 'usr_3910c2e',
    name: 'Amira Al-Husseini',
    email: 'amira.fashion@boutique.ae',
    phoneNumber: '+971 52 987 6543',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    tier: 'pro',
    tierExpiresAt: '2026-11-15T00:00:00Z',
    autoRenew: true,
    status: 'active',
    joinedAt: '2024-08-01T14:10:00Z',
    lastActiveAt: '2026-08-14T06:45:00Z',
    devicesCount: 2,
    ordersCount: 89,
    totalSpent: 9240.50,
    fcmTokenCount: 2,
    country: 'United Arab Emirates',
    notes: 'Dubai flagship boutique merchant. Uses premium catalog analytics.',
    storageQuotaMb: 5120,
    usedStorageMb: 1980,
  },
  {
    id: 'usr_5182f7d',
    name: 'Yousef Nader',
    email: 'yousef.nader@gmail.com',
    phoneNumber: '+965 99 876 543',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    tier: 'free',
    tierExpiresAt: null,
    autoRenew: false,
    status: 'active',
    joinedAt: '2025-01-10T12:00:00Z',
    lastActiveAt: '2026-08-13T19:15:00Z',
    devicesCount: 1,
    ordersCount: 14,
    totalSpent: 620.00,
    fcmTokenCount: 1,
    country: 'Kuwait',
    notes: 'Retail buyer experimenting with localized seller shop.',
    storageQuotaMb: 1024,
    usedStorageMb: 410,
  },
  {
    id: 'usr_7721d3b',
    name: 'Layla Al-Khatib',
    email: 'layla.khatib@crafts.qa',
    phoneNumber: '+974 33 456 789',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    tier: 'pro',
    tierExpiresAt: '2026-09-30T00:00:00Z',
    autoRenew: true,
    status: 'active',
    joinedAt: '2024-11-20T08:30:00Z',
    lastActiveAt: '2026-08-14T05:10:00Z',
    devicesCount: 2,
    ordersCount: 156,
    totalSpent: 14320.00,
    fcmTokenCount: 2,
    country: 'Qatar',
    notes: 'Artisan marketplace creator. High engagement with push alerts.',
    storageQuotaMb: 5120,
    usedStorageMb: 3100,
  },
  {
    id: 'usr_1049e6c',
    name: 'Omar Farooq',
    email: 'omar.farooq@logistics.om',
    phoneNumber: '+968 91 234 567',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    tier: 'free',
    tierExpiresAt: null,
    autoRenew: false,
    status: 'pending',
    joinedAt: '2026-08-10T16:40:00Z',
    lastActiveAt: '2026-08-11T09:12:00Z',
    devicesCount: 1,
    ordersCount: 2,
    totalSpent: 45.00,
    fcmTokenCount: 1,
    country: 'Oman',
    notes: 'Account under identity verification for merchant onboarding.',
    storageQuotaMb: 1024,
    usedStorageMb: 95,
  },
  {
    id: 'usr_6631b8a',
    name: 'Nour El-Din',
    email: 'nour.eldin@tradeegypt.eg',
    phoneNumber: '+20 10 2345 6789',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    tier: 'enterprise',
    tierExpiresAt: '2027-06-30T00:00:00Z',
    autoRenew: true,
    status: 'active',
    joinedAt: '2023-10-05T15:00:00Z',
    lastActiveAt: '2026-08-14T07:40:00Z',
    devicesCount: 4,
    ordersCount: 934,
    totalSpent: 78900.00,
    fcmTokenCount: 4,
    country: 'Egypt',
    notes: 'Cairo logistics partner. Multi-branch POS integration.',
    storageQuotaMb: 20480,
    usedStorageMb: 11200,
  },
  {
    id: 'usr_2491c5a',
    name: 'Fatima Al-Majid',
    email: 'fatima.majid@bh-retail.com',
    phoneNumber: '+973 39 876 543',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    tier: 'pro',
    tierExpiresAt: '2026-10-15T00:00:00Z',
    autoRenew: true,
    status: 'active',
    joinedAt: '2025-03-01T11:00:00Z',
    lastActiveAt: '2026-08-13T22:05:00Z',
    devicesCount: 2,
    ordersCount: 67,
    totalSpent: 5670.00,
    fcmTokenCount: 2,
    country: 'Bahrain',
    notes: 'Manama boutique store. Upgraded for automated inventory syncing.',
    storageQuotaMb: 5120,
    usedStorageMb: 1840,
  },
  {
    id: 'usr_9981f1e',
    name: 'Suspicious Trade Bot 42',
    email: 'bot42_crawler@spamhost.xyz',
    phoneNumber: '+1 555 019 2831',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    tier: 'free',
    tierExpiresAt: null,
    autoRenew: false,
    status: 'suspended',
    joinedAt: '2026-07-22T03:14:00Z',
    lastActiveAt: '2026-07-24T18:00:00Z',
    devicesCount: 12,
    ordersCount: 0,
    totalSpent: 0.00,
    fcmTokenCount: 0,
    country: 'United States',
    notes: 'Suspended automatically due to scraping rate-limit violations.',
    storageQuotaMb: 1024,
    usedStorageMb: 12,
  },
];

export const AUDIENCE_SEGMENTS: AudienceSegmentDefinition[] = [
  {
    id: 'all_users',
    name: 'All Registered Users',
    description: 'Broadcast to all active mobile device push tokens across iOS & Android.',
    estimatedCount: 184500,
    icon: 'Users',
    category: 'activity',
  },
  {
    id: 'pro_subscribers',
    name: 'Pro & Enterprise Tier',
    description: 'High-value paying subscribers eligible for VIP perks and beta feature previews.',
    estimatedCount: 28400,
    icon: 'Crown',
    category: 'tier',
  },
  {
    id: 'inactive_7_days',
    name: 'Dormant (> 7 Days Inactive)',
    description: 'Re-engagement segment for users who opened the app over a week ago.',
    estimatedCount: 42100,
    icon: 'UserX',
    category: 'activity',
  },
  {
    id: 'ios_users',
    name: 'iOS Apple Devices (APNs)',
    description: 'Devices registered with Apple APNs payload handlers and live badges.',
    estimatedCount: 98700,
    icon: 'Smartphone',
    category: 'platform',
  },
  {
    id: 'android_users',
    name: 'Android Devices (FCM v1)',
    description: 'Devices registered via standard Google Play Services push channels.',
    estimatedCount: 85800,
    icon: 'Smartphone',
    category: 'platform',
  },
  {
    id: 'high_value_spenders',
    name: 'Top 10% Spenders',
    description: 'Merchants and power shoppers with lifetime orders exceeding $5,000.',
    estimatedCount: 14200,
    icon: 'TrendingUp',
    category: 'behavior',
  },
];

export const INITIAL_CAMPAIGNS: NotificationCampaign[] = [
  {
    id: 'camp_7819_summer',
    title: '🎉 Summer Flash Sale: Up to 40% Off!',
    body: 'Exclusive weekend discounts on your top saved merchant catalogs. Tap to explore!',
    imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&auto=format&fit=crop&q=80',
    deepLink: 'tijarah://promotions/summer_2026',
    audience: 'all_users',
    audienceEstimatedCount: 184500,
    status: 'completed',
    priority: 'high',
    sound: 'alert',
    createdAt: '2026-08-10T10:00:00Z',
    sentAt: '2026-08-10T14:00:00Z',
    createdBy: {
      adminId: 'admin_chloe_mkt',
      adminName: 'Chloe Dupont',
      adminRole: 'Marketing Admin',
    },
    metrics: {
      totalSent: 184500,
      deliveredCount: 178920,
      openedCount: 42350,
      clickedCount: 29400,
      failedCount: 5580,
      deliveryRatePct: 96.9,
      openRatePct: 23.7,
    },
  },
  {
    id: 'camp_8922_pro_perks',
    title: '⚡ New Pro Analytics Dashboard is Live',
    body: 'Unlock real-time customer heatmaps and inventory forecasting with your Pro membership.',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
    deepLink: 'tijarah://dashboard/analytics',
    audience: 'pro_subscribers',
    audienceEstimatedCount: 28400,
    status: 'completed',
    priority: 'normal',
    sound: 'default',
    createdAt: '2026-08-12T09:30:00Z',
    sentAt: '2026-08-12T11:00:00Z',
    createdBy: {
      adminId: 'admin_chloe_mkt',
      adminName: 'Chloe Dupont',
      adminRole: 'Marketing Admin',
    },
    metrics: {
      totalSent: 28400,
      deliveredCount: 27950,
      openedCount: 11840,
      clickedCount: 8910,
      failedCount: 450,
      deliveryRatePct: 98.4,
      openRatePct: 42.4,
    },
  },
  {
    id: 'camp_9011_retention',
    title: 'We miss you! Special 20% discount coupon',
    body: 'Check out the new arrivals added to your local feed this week.',
    deepLink: 'tijarah://feed/recommended',
    audience: 'inactive_7_days',
    audienceEstimatedCount: 42100,
    status: 'scheduled',
    scheduledFor: '2026-08-16T15:00:00Z',
    priority: 'normal',
    sound: 'default',
    createdAt: '2026-08-14T08:00:00Z',
    createdBy: {
      adminId: 'admin_chloe_mkt',
      adminName: 'Chloe Dupont',
      adminRole: 'Marketing Admin',
    },
    metrics: {
      totalSent: 0,
      deliveredCount: 0,
      openedCount: 0,
      clickedCount: 0,
      failedCount: 0,
      deliveryRatePct: 0,
      openRatePct: 0,
    },
  },
];

export const INITIAL_CRASH_ISSUES: CrashIssue[] = [
  {
    id: 'issue_cr_4091',
    title: 'NullPointerException in PaymentSheetPresenter.onSuccess',
    subtitle: 'com.tijarah.app.checkout.PaymentSheetPresenter.kt:142',
    exceptionType: 'java.lang.NullPointerException',
    severity: 'fatal',
    status: 'investigating',
    firstSeen: '2026-08-11T12:30:00Z',
    lastSeen: '2026-08-14T07:15:00Z',
    totalEvents: 342,
    impactedUsersCount: 188,
    affectedVersions: ['v3.4.1', 'v3.4.2'],
    assignedTo: 'david.chen@tijarah.app',
    rootCauseNotes: 'Happens when gateway callback returns nullable receipt object on slow 3G connectivity.',
    stackTrace: [
      'java.lang.NullPointerException: Parameter specified as non-null is null: method com.tijarah.app.checkout.ReceiptData.<init>',
      '  at com.tijarah.app.checkout.PaymentSheetPresenter.onSuccess(PaymentSheetPresenter.kt:142)',
      '  at com.tijarah.core.network.StripeCallbackHandler.onResult(StripeCallbackHandler.kt:89)',
      '  at com.stripe.android.paymentsheet.PaymentSheetViewModel$1.invokeSuspend(PaymentSheetViewModel.kt:312)',
      '  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)',
      '  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)',
      '  at android.os.Handler.handleCallback(Handler.java:942)',
    ],
  },
  {
    id: 'issue_cr_5821',
    title: 'Out of Memory Exception in ProductGalleryCache',
    subtitle: 'com.tijarah.app.ui.gallery.ImageBitmapDecoder.kt:88',
    exceptionType: 'java.lang.OutOfMemoryError',
    severity: 'fatal',
    status: 'open',
    firstSeen: '2026-08-08T09:00:00Z',
    lastSeen: '2026-08-14T04:20:00Z',
    totalEvents: 89,
    impactedUsersCount: 64,
    affectedVersions: ['v3.4.0', 'v3.4.1', 'v3.4.2'],
    rootCauseNotes: 'Uncompressed 4K vendor banners exceeding Android heap limit on 3GB RAM devices.',
    stackTrace: [
      'java.lang.OutOfMemoryError: Failed to allocate a 32400000 byte allocation with 4194304 free bytes',
      '  at dalvik.system.VMRuntime.newNonMovableArray(Native Method)',
      '  at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)',
      '  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:792)',
      '  at com.tijarah.app.ui.gallery.ImageBitmapDecoder.decodeSampled(ImageBitmapDecoder.kt:88)',
      '  at com.tijarah.app.ui.gallery.ProductImageAdapter.onBindViewHolder(ProductImageAdapter.kt:54)',
    ],
  },
  {
    id: 'issue_cr_2209',
    title: 'ANR: Input dispatching timed out (SearchAutoCompleteTextView)',
    subtitle: 'com.tijarah.app.search.SearchAutoCompleteTextView.kt:55',
    exceptionType: 'ApplicationNotResponding',
    severity: 'anr',
    status: 'resolved',
    firstSeen: '2026-07-28T14:10:00Z',
    lastSeen: '2026-08-05T19:00:00Z',
    totalEvents: 612,
    impactedUsersCount: 405,
    affectedVersions: ['v3.3.8', 'v3.3.9'],
    assignedTo: 'david.chen@tijarah.app',
    rootCauseNotes: 'Debounce coroutine was dispatched on main looper instead of IO dispatcher. Fixed in v3.4.0.',
    stackTrace: [
      '"main" prio=5 tid=1 Blocked',
      '  at com.tijarah.app.search.LocalTrieSearch.findPrefixMatches(LocalTrieSearch.kt:55)',
      '  at com.tijarah.app.search.SearchAutoCompleteTextView.onTextChanged(SearchAutoCompleteTextView.kt:76)',
      '  at android.widget.TextView.sendOnTextChanged(TextView.java:11452)',
      '  at android.widget.TextView.handleTextChanged(TextView.java:11528)',
    ],
  },
];

export const INITIAL_CRASH_METRICS: CrashMetricsSummary = {
  crashFreeUsersPct: 99.78,
  crashFreeSessionsPct: 99.91,
  totalCrashes24h: 37,
  openIssuesCount: 2,
  anrCount24h: 3,
  topOffendingVersion: 'v3.4.2 (Android)',
};

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud_99182',
    timestamp: '2026-08-14T07:45:10Z',
    action: 'admin_custom_claims_updated',
    actor: {
      uid: 'admin_sarah_super',
      displayName: 'Sarah Al-Mansoor',
      email: 'sarah.almansoor@tijarah.app',
      role: 'super_admin',
    },
    targetResource: {
      type: 'admin',
      id: 'admin_david_pm',
      name: 'David Chen',
    },
    description: 'Updated permissions for David Chen: added crashlytics:manage_issues custom claim.',
    changes: {
      before: { permissions: ['users:view', 'users:edit', 'users:manage_subscription'] },
      after: { permissions: ['users:view', 'users:edit', 'users:manage_subscription', 'crashlytics:view', 'crashlytics:manage_issues'] },
    },
    ipAddress: '192.168.1.104',
  },
  {
    id: 'aud_99181',
    timestamp: '2026-08-14T06:40:22Z',
    action: 'user_subscription_changed',
    actor: {
      uid: 'admin_david_pm',
      displayName: 'David Chen',
      email: 'david.chen@tijarah.app',
      role: 'app_manager',
    },
    targetResource: {
      type: 'user',
      id: 'usr_3910c2e',
      name: 'Amira Al-Husseini',
    },
    description: 'Extended Pro subscription until Nov 15, 2026 (+3 months loyalty perk).',
    changes: {
      before: { tier: 'pro', expiresAt: '2026-08-15T00:00:00Z' },
      after: { tier: 'pro', expiresAt: '2026-11-15T00:00:00Z' },
    },
    ipAddress: '10.0.4.28',
  },
  {
    id: 'aud_99180',
    timestamp: '2026-08-12T11:00:00Z',
    action: 'fcm_broadcast_dispatched',
    actor: {
      uid: 'admin_chloe_mkt',
      displayName: 'Chloe Dupont',
      email: 'chloe.dupont@tijarah.app',
      role: 'marketing_admin',
    },
    targetResource: {
      type: 'campaign',
      id: 'camp_8922_pro_perks',
      name: '⚡ New Pro Analytics Dashboard is Live',
    },
    description: 'Broadcasted push notification campaign to segment "Pro & Enterprise Tier" (28,400 target tokens).',
    changes: {
      before: null,
      after: { targetAudience: 'pro_subscribers', priority: 'normal', deliveryCount: 27950 },
    },
    ipAddress: '172.16.8.91',
  },
  {
    id: 'aud_99179',
    timestamp: '2026-08-11T16:20:00Z',
    action: 'crash_issue_status_updated',
    actor: {
      uid: 'admin_david_pm',
      displayName: 'David Chen',
      email: 'david.chen@tijarah.app',
      role: 'app_manager',
    },
    targetResource: {
      type: 'crash_issue',
      id: 'issue_cr_4091',
      name: 'NullPointerException in PaymentSheetPresenter',
    },
    description: 'Changed issue status from "open" to "investigating". Assigned to David Chen.',
    changes: {
      before: { status: 'open' },
      after: { status: 'investigating', assignedTo: 'david.chen@tijarah.app' },
    },
    ipAddress: '10.0.4.28',
  },
];
